spring:
  application:
    name: pocket-reminder
  # datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db/sampledb
    username: sa
    password:

server:
  port: 8080

pocket:
  consumer-key: ${CONSUMER_KEY}
  get-url: https://getpocket.com/v3/get
  token-url: https://getpocket.com/v3/oauth/request
  redirect-url: https://getpocket.com/auth/authorize
  auth-url: https://getpocket.com/v3/oauth/authorize
  pocket-url: http://localhost:8080/index

management:
  endpoints:
    web:
      exposure:
        include: '*'
---

spring:
  profiles: heroku
pocket:
  pocket-url: https://pocket-reminder.herokuapp.com/index